import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { routing } from '@/lib/i18n/routing';
import { hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { setRequestLocale } from 'next-intl/server';
import Navbar from '@/components/layout/navbar';
import 'swiper/css';
import '../globals.css';
import { getServicesList } from '@/actions';

const dmSans = DM_Sans({
  variable: '--font-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'io-task',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const services = await getServicesList();
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html
      lang={locale}
      dir={locale === 'en' ? 'ltr' : 'rtl'}>
      <body className={`${dmSans.variable}  antialiased`}>
        <Navbar servicesList={services} />
        <main className='min-h-[calc(100dvh-71px)]'>{children}</main>
      </body>
    </html>
  );
}
